In [ ]:
class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        hashmap = {}
        for index, item in enumerate(nums):
            if hashmap.has_key(target - item):
                return hashmap[target-item],index
            hashmap[item] = index

In [ ]:
# Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, x):
#         self.val = x
#         self.next = None

class Solution(object):
    def addTwoNumbers(self, l1, l2):
        """
        :type l1: ListNode
        :type l2: ListNode
        :rtype: ListNode
        """
        result = ListNode(0)
        result_tail = result
        carry = 0
        
        while l1 or l2 or carry:            
            val1  = (l1.val if l1 else 0)
            val2  = (l2.val if l2 else 0)
            carry, out = divmod(val1+val2 + carry, 10)

            result_tail.next = ListNode(out)
            result_tail = result_tail.next

            l1 = (l1.next if l1 else None)
            l2 = (l2.next if l2 else None)

        return result.next

In [ ]:
class Solution(object):
    def lengthOfLongestSubstring(self, s):
        """
        :type s: str
        :rtype: int
        """
        dicts = {}
        maxlength = start = 0
        for i,value in enumerate(s):
            if value in dicts:
                sums = dicts[value] + 1
                if sums > start:
                    start = sums
            num = i - start + 1
            if num > maxlength:
                maxlength = num
            dicts[value] = i
        return maxlength

In [ ]:
class Solution(object):
    def findMedianSortedArrays(self, nums1, nums2):
        """
        :type nums1: List[int]
        :type nums2: List[int]
        :rtype: float
        """
        
        nums1 = nums1 + nums2
        nums1.sort()
        if len(nums1)%2:#奇数
            median = nums1[len(nums1)//2]
        else:#偶数
            median = (nums1[(len(nums1)/2)-1]+nums1[len(nums1)/2])/2.0
        return median

In [ ]:
class Solution(object):
    def longestPalindrome(self, s):
        """
        :type s: str
        :rtype: str
        """
        length = len(s)
        
        if length <= 1:
            return s
        
        start = end = 0
        
        for i in range(length):
            max_len_1 = self.get_max_len(s, i, i + 1)
            max_len_2 = self.get_max_len(s, i, i)
            max_len = max(max_len_1, max_len_2)
            
            if max_len > end - start:
                start = i - (max_len - 1)//2
                end = i + max_len//2
                
        return s[start: end+1]
    
    
    def get_max_len(self, s, left, right):
        length = len(s)
        while left >= 0 and right < length and s[left] == s[right]:
            left -= 1
            right += 1
        return right - left - 1
        

In [ ]:
class Solution(object):
    def convert(self, s, numRows):
        """
        :type s: str
        :type numRows: int
        :rtype: str
        """
        
        result = ""
        length = len(s)
        
        if numRows == 1 or length == 1:
            return s
        
        for i in range(numRows):
            m = 0
            if len(result) == length:
                return result
            
            if i == 0 or i == (numRows-1):
                while (i + m*(2*numRows-2)) <= length-1:
                    result = result + s[i + m*(2*numRows-2)]
                    m = m+1

            else:
                result = result + s[i]
                m = 1
                try:
                    while (i + m*(2*numRows - 2) + -1*2*i) <= length-1:
                        result = result + s[i + m*(2*numRows-2) + -1*2*i]
                        result = result + s[i + m*(2*numRows-2)]
                        m = m+1
                except IndexError:
                    continue
                    
        return result
                
        

In [ ]:
class Solution(object):
    def reverse(self, x):
        """
        :type x: int
        :rtype: int
        """
        result = int(str(abs(x))[::-1])
        
        if result>2147483647 or result<-2147483647:
            return 0
        else:
            if x>0:
                return result
            else:
                return -result


In [ ]:
class Solution(object):
    def myAtoi(self, s):
        """
        :type s: str
        :rtype: int
        """
        import re
        match = re.match(r'^\s*([+-]?\d+)', s)
        return min(max((int(match.group(1)) if match else 0), -2**31), 2**31 - 1)

In [ ]:
class Solution(object):
    def isPalindrome(self, x):
        """
        :type x: int
        :rtype: bool
        """
        x = str(x)
        if x==x[::-1]:
            return True
        else: 
            return False

In [ ]:
class Solution(object):
    def isMatch(self, s, p):
        """
        :type s: str
        :type p: str
        :rtype: bool
        """
        import re
        match = re.match(p, s)
        if match == None:
            return False
        else:
            start,end = match.span()
            if end != (len(s)) or start != 0:
                return False
            else:
                return True
                

In [9]:
a = [[2,   3,  5,  7, 11],
     [3,  13, 17, 19, 23],
     [5,  17, 29, 31, 37],
     [7,  19, 31, 41, 43],
     [11, 23, 37, 43, 47]]

# b = [[0,   3, 10, 21, 44],
#      [3,   0, 17, 38, 69],
#      [10, 17,  0, 31, 74],
#      [21, 38, 31,  0, 43],
#      [44, 69, 74, 43,  0]]

c = [[0,   0,  0,  0,  0],
     [3,   0,  0,  0,  0],
     [10, 17,  0,  0,  0],
     [21, 38, 31,  0,  0],
     [44, 69, 74, 43,  0]]

In [10]:
import numpy as np
a = np.array(a)
# b = np.array(b)
c = np.array(c)

In [11]:
r = c/a
print(r)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]]
